services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - wordpress-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mariadb
    networks:
      - inception

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress-files:/var/lib/www/wordpress
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
    container_name: wordpress
    networks:
      - inception

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:80"
    volumes:
      - wordpress-files:/var/lib/www/wordpress
    container_name: nginx
    networks:
      - inception

volumes:
  wordpress-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seojilee/data/database
  wordpress-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seojilee/data/files

## might change later

networks:
  inception:
