services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - wordpress-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mariadb
    networks:
      - inception

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:80"
    container_name: nginx
    networks:
      - inception

volumes:
  wordpress-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seojilee/data
## might change later

networks:
  inception:
